version: '3.8'

services:
  web:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:8000 src.project.core.asgi:application -w ${GUNICORN_WORKERS} -k uvicorn.workers.UvicornWorker
    ports:
      - 8000:8000
    networks:
      - mms_network
    external_links:
      - postgres:postgres
      - redis:redis
    env_file:
      - .env.development

networks:
  mms_network:
    driver: bridge
