[tool.towncrier]
    package = ''
    package_dir = 'src'
    filename = 'CHANGELOG.md'
    title_format = '{version} ({project_date})'
    directory = 'changelog'
    template = 'towncrier_template.rst'
    # issue_format = "`#{issue} <https://github.com/python-attrs/attrs/issues/{issue}>`_"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Misc"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "health"
        name = "Health"
        showcontent = true
