# Generated by Django 3.2.10 on 2021-12-16 23:48

import django.core.validators
from django.db import migrations, models
import project.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativado')),
                ('name', project.core.models.UpperCaseCharField(help_text='Informe o nome completo do cliente.', max_length=255, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and spaces.', regex='^[a-z A-Z]*$')], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Informe o CPF do cliente. Somente números.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='This field must contain only numbers.', regex='^[0-9]*$'), django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('promoter', models.CharField(blank=True, help_text='Opcional: Informe o nome da pessoa que vendeu o ingresso.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='This field must contain only letters and spaces.', regex='^[a-z A-Z]*$')], verbose_name='Promotor')),
                ('note', models.TextField(blank=True, help_text='Opcional: Informe alguma observação sobre o ingresso.', null=True, verbose_name='Observação')),
                ('validated', models.BooleanField(default=False, help_text='Se preenchido o ingresso já foi validado.', verbose_name='Validado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'ordering': ['-created_at'],
            },
        ),
    ]
