# Generated by Django 3.2.10 on 2021-12-17 00:20
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from project.tickets.models import Tickets


def create_permission(apps, schema_editor):
    content_type = ContentType.objects.get_for_model(Tickets)
    Permission.objects.create(
        codename='validate_ticket',
        name='Can validate Ticket',
        content_type=content_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permission),
    ]
