# Generated by Django 3.2.4 on 2021-06-06 23:33

from django.db import migrations, models
import project.core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMovingAverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('timestamp', models.IntegerField(verbose_name='Timestamp')),
                ('pair', project.core.models.UpperCaseCharField(max_length=10, verbose_name='Pair')),
                ('precision', models.CharField(max_length=10, verbose_name='Precision')),
                ('mms_20', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Simple Moving Average of 20')),
                ('mms_50', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Simple Moving Average of 50')),
                ('mms_200', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Simple Moving Average of 200')),
            ],
            options={
                'verbose_name': 'Simple Moving Average',
                'verbose_name_plural': 'Simple Moving Average',
                'db_table': 'ind_simplemovingaverage',
                'unique_together': {('timestamp', 'pair', 'precision')},
            },
        ),
    ]
